Assumptions for work depth analysis
spcl/dace-vscode pull request #234
Opened 2023-09-04 12:06 UTC by hodelcl

This PR enables the user to enter assumptions for the symbols before calling the work depth analysis.

It uses a VS code `InputBox` to handle the input. Validity of the input is checked by a regex. If the check passes, the assumptions are forwarded to the work depth analysis.

The corresponding PR to the dace repo can be found [here](https://github.com/spcl/dace/pull/1363).

2023-09-18 08:59 UTC, phschaad requested changes
Very nice, thank you :-) Small changes only

2023-09-18 08:59 UTC, phschaad commented on src/components/dace_interface.ts
> +                vscode.window.showInputBox({
This is quite some code repetition, is it possible to factor this out into a separate small function? (Showing the prompt, checking for the format, showing error message if violated, etc.)

2023-09-18 08:59 UTC, phschaad commented on backend/run_dace.py
> +from dace_vscode import depth, transformations
Can't the `dace_vscode.arith_ops` module be removed entirely now?

2023-09-18 08:59 UTC, phschaad commented on backend/dace_vscode/depth.py
> +def get_work(sdfg_json, assumptions):
This module should now probably be renamed to `work_depth` or something :-)

2023-09-28 07:30 UTC, hodelcl commented
I integrated all your comments:

- put the `InputBox` for the assumptions and the input checking in separate functions,
- deleted the `dace_vscode.arith_ops` module,
- renamed the `depth` module to `work_depth`.

2023-10-02 13:46 UTC, phschaad approved these changes
LGTM, thanks

2023-10-02 13:46 UTC, merged