Performance improvements with attributes / info panel
spcl/dace-vscode pull request #269
Opened 2024-12-18 08:23 UTC by phschaad

2025-12-07 18:11 UTC, tbennun requested changes
Looks great! Very minor comments and I am only wondering if some of the new async vs. synchronous scheme helps or detracts from plugin responsivity. Please comment.

2025-12-07 18:11 UTC, tbennun commented on src/common/messaging/icpc_messaging_component.ts
> +                void this.handleRequest(
what's this syntax?

2025-12-07 18:11 UTC, tbennun commented on src/components/messaging/icpc_extension_messaging_component.ts
> +        this.initializeTarget(webview as unknown as WebviewApi<unknown>);
such an ugly pattern. Is it possible to make the class hierarchy such that WebviewApi and Webview are related through a common ancestor inferface? We can't control Webview

2025-12-07 18:11 UTC, tbennun commented on src/components/sdfg_editor/compressed_sdfg_editor.ts
> +            const compressed = gzipSync(sdfg).buffer;
nice! saves memory

2025-12-07 18:11 UTC, tbennun commented on src/debugger/dace_debugging_session.ts
> +        const portNum: string = String(DACE_DEBUG_PORT);
does the debug functionality still work?

2025-12-07 18:11 UTC, tbennun commented on src/utils/sdfg_meta_dict.json
> +    "gpu_force_syncthreads": {
Is this from 1.0.2 or 2.0.0-alpha1?

2025-12-07 18:11 UTC, tbennun commented on src/utils/utils.ts
> +    if (document) {
very nice change

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/sdfv/properties/properties.ts
> +                    value = parseInt(value);
this can create a situation in which value is not a `number` but still returned? you can keep this but I am not sure what is the purpose of this function.

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/sdfv/renderer/vscode_renderer.ts
> +                            src: startId,
great

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/sdfv/transformation/transformation.ts
> +                    String(transformation.state_id) + '/' + String(id) +
toString? apply everywhere in this file

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/sdfv/attributes_table.scss
> +/* Copyright 2020-2024 ETH Zurich and the DaCe-VSCode authors.
```suggestion
/* Copyright 2020-2025 ETH Zurich and the DaCe-VSCode authors.
```

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/sdfv/vscode_sdfv.scss
```suggestion
/* Copyright 2020-2025 ETH Zurich and the DaCe-VSCode authors.
```

2025-12-07 18:11 UTC, tbennun commented on src/webclients/components/transformations/transformations.ts
> +                        String(this.cfgId) + '/' + String(id) + '/-1/-1'
tostring again

2025-12-07 18:11 UTC, tbennun commented on package.json
> +    "description": "An integrated optimization environment powered by DaCe",
:)

2025-12-07 18:11 UTC, tbennun commented on package.json
> +                        "type": "string",
I forget, do we/vscode have a type with a color picker?

2025-12-08 08:29 UTC, phschaad commented on src/common/messaging/icpc_messaging_component.ts
> +                void this.handleRequest(
`handleRequest` returns a Promise, and with the more strict linting and verification rules I added, you have to handle a Promise (await, or catch all exceptions), or explicitly let it go into nothing if you don't need the result - which you do with `void`.

2025-12-08 08:30 UTC, phschaad commented on src/utils/sdfg_meta_dict.json
> +    "gpu_force_syncthreads": {
`2.0.0-alpha1`

2025-12-09 08:35 UTC, phschaad commented on package.json
> +                        "type": "string",
the webclient has one, so if you set this setting through the webview, you get a color picker. VSCode settings sadly only support strings so far. But once they support it, a simple change of the type here would make use of it.

2025-12-09 09:22 UTC, phschaad commented on src/components/messaging/icpc_extension_messaging_component.ts
> +        this.initializeTarget(webview as unknown as WebviewApi<unknown>);
Currently not, because as you say, we don't control `Webview`, and it is an incomplete type declaration. To solve this, someone created the `vscode-webview` type declaration, which is where `WebviewApi` comes from. Since the two do not share a common supertype, conversion between them is currently only possible through `unknown`. However, this is something that Microsoft has at some point promised to fix, so I am hoping the `Webview` type will at some point become more complete - which is when we could drop this.

2025-12-09 09:31 UTC, phschaad commented on src/webclients/components/sdfv/properties/properties.ts
> +                    value = parseInt(value);
Yes, we return the value even if it is not a number - beforehand we tried to convert anything to an integer and just return it as is if it could not be converted. The issue with that, is that values such as `undefined` or `null` were then also converted, which lead to `NaN` return values as opposed to `undefined` / `null`. To avoid this, we just check that the type is a string first now, since we want `undefined` as a return value if that is the property value.

2025-12-09 10:02 UTC, phschaad commented on src/debugger/dace_debugging_session.ts
> +        const portNum: string = String(DACE_DEBUG_PORT);
No the debug functionality was removed from the UI around [1.5 years ago](https://github.com/spcl/dace-vscode/pull/260/files#diff-3bdabd7004490ac675177fb46f58afe062d97aa8d98b676cd9bdcdc51e267e45L145), but in working on this PR, one of the items that has made it onto the issues list for the upcoming weeks, is a PR to revive this functionality ;-)

2025-12-09 14:32 UTC, tbennun approved these changes

2025-12-09 16:09 UTC, merged